### ISSUE TITLE
Bug: vote_type can be type DAO | str, but DAO has no function startswith

### ISSUE THREAD

**Issue by martinkrung** [bout3fiddy/curve-dao#4]
vote_type can be type DAO or str, if DAO then this error raises

``Traceback (most recent call last):
  File "/home/m/dev/curve/arbitrum_dlc_pool_adjust/arbitrumvotevalidation.py", line 61, in <module>
    vote_id = curve_dao.create_vote(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/dev/curve/arbitrum_dlc_pool_adjust/.venv/lib/python3.12/site-packages/curve_dao/__init__.py", line 30, in create_vote
    evm_script = prepare_evm_script(dao, actions, etherscan_api_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/dev/curve/arbitrum_dlc_pool_adjust/.venv/lib/python3.12/site-packages/curve_dao/vote_utils.py", line 40, in prepare_evm_script
    get_dao_parameters(dao)["agent"], name="AragonAgent", api_key=etherscan_api_key
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/dev/curve/arbitrum_dlc_pool_adjust/.venv/lib/python3.12/site-packages/curve_dao/addresses.py", line 44, in get_dao_parameters
    if vote_type.startswith("0x"):
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'startswith'``

code line: https://github.com/bout3fiddy/curve-dao/blob/main/curve_dao/addresses.py#L40

**Comment by romanagureev** [comment]
According to traceback you put `dict`. Probably `curve_dao.addresses.CURVE_DAO_OWNERSHIP` instead of `curve_dao.addresses.DAO.OWNERSHIP`.
